# Generated by Django 5.2.6 on 2025-10-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_videocallsession_room_remove_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
